CREATE EXTERNAL TABLE ${env:hiveSchema}.CLM_TARGET
(
 CLM_ID STRING,
 CLM_FORM CHAR(1),
 CLM_TYPE CHAR(1),
 TOB INT,
 PRV_ID INT,
 PHY_ID INT,
 PROC_DT STRING
)
PARTITIONED BY (VIEWDATE STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '${env:hiveWarehousePath}/clm_target'
;