CREATE EXTERNAL TABLE ${env:hiveSchema}.INCRSTAGING
(
 SRC_CLM_ID STRING,
 SRC_CLM_FORM CHAR(1),
 SRC_CLM_TYPE CHAR(1),
 SRC_TOB INT,
 SRC_PRV_ID INT,
 SRC_PHY_ID INT,
 SRC_PROC_DT STRING
 TGT_CLM_FORM CHAR(1),
 TGT_CLM_TYPE CHAR(1),
 TGT_TOB INT,
 TGT_PRV_ID INT,
 TGT_PHY_ID INT,
 TGT_PROC_DT STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '${env:hiveWarehousePath}/incrstaging';